# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import config_pb2 as config__pb2


class AuthStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Verification = channel.unary_unary(
                '/authorization.Auth/Verification',
                request_serializer=config__pb2.Token.SerializeToString,
                response_deserializer=config__pb2.UserInfo.FromString,
                )


class AuthServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Verification(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Verification': grpc.unary_unary_rpc_method_handler(
                    servicer.Verification,
                    request_deserializer=config__pb2.Token.FromString,
                    response_serializer=config__pb2.UserInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'authorization.Auth', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Auth(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Verification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/authorization.Auth/Verification',
            config__pb2.Token.SerializeToString,
            config__pb2.UserInfo.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
