version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  mq:
    image: rabbitmq:3.6.6-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    ports:
      - "5672:5672"
      - "15672:15672"

  web:
    build:
      context: shop
      dockerfile: Dockerfile
    command: sh -c "cd shop && chmod +x run && ./run"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - auth

  auth:
    build:
      context: authorization
      dockerfile: Dockerfile
    command: sh -c "cd authorization && chmod +x run && ./run"
    volumes:
      - .:/auth_code
    ports:
      - "8001:8001"
    depends_on:
      - db
      - mq

  notify:
    build:
      context: notify
      dockerfile: notify/Dockerfile
    command: sh -c "cd notify && chmod +x run && ./run"
    ports:
      - "8002:8002"
    depends_on:
      - mq