version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: ./run
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
