#!/bin/bash
echo "Wait for database start"
chmod +x wait_for_it.sh
wait_for_it.sh db:5432
echo "Apply database migrations"
python manage.py migrate
echo "Starting server"
python manage.py runserver 0.0.0.0:8000
